-- Add a permanent UUID identity per employee, independent of the mutable emp_code
-- and independent of the integer id. Auto-generated by the DB on every insert.
-- Existing employees get a UUID too (for schema consistency / future-proofing),
-- but their QR files are NEVER regenerated, so this column has no effect on them.
-- New employees' QR payloads use this uuid instead of the integer id.

ALTER TABLE employees
  ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE employees
  ADD CONSTRAINT employees_uuid_key UNIQUE (uuid);
